<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.Q0z.Yor.Symfony\Component\Form\FormEvent' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.Q0z.Yor": it references class "Symfony\\Component\\Form\\FormEvent" but no such service exists.');
