<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Q0z.Yor' shared service.

return $this->privates['.service_locator.Q0z.Yor'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('event' => function (): \Symfony\Component\Form\FormEvent {
    return ($this->privates['.errored..service_locator.Q0z.Yor.Symfony\Component\Form\FormEvent'] ?? $this->load('getFormEventService.php'));
}));
