<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEUxsQxe\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEUxsQxe/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerEUxsQxe.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerEUxsQxe\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerEUxsQxe\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'EUxsQxe',
    'container.build_id' => '64ca2f54',
    'container.build_time' => 1538333711,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerEUxsQxe');
